# Generated by Django 5.2.8 on 2025-11-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aluno_foto_aluno_turma_atual_aluno_user_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('prova', 'Prova'), ('trabalho', 'Entrega de Trabalho'), ('evento', 'Evento Escolar'), ('reuniao', 'Reunião')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.turma')),
            ],
        ),
    ]
