# Generated by Django 5.2.8 on 2025-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_professor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Notas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Trancado', 'Trancado'), ('Concluido', 'Concluído')], default='Ativo', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('matricula', 'disciplina', 'data_aula')},
        ),
    ]
