# Generated by Django 5.2.8 on 2025-12-08 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_aluno_options_alter_aviso_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField(default=40)),
                ('tipo', models.CharField(default='Sala de Aula', max_length=50)),
                ('bloco', models.CharField(blank=True, max_length=50, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AddField(
            model_name='aviso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aviso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='destinatario',
            field=models.CharField(choices=[('todos', 'Todos'), ('alunos', 'Alunos'), ('professores', 'Professores'), ('turma', 'Turma Específica')], default='todos', max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('tipo', models.CharField(choices=[('apostila', 'Apostila'), ('exercicio', 'Lista de Exercícios'), ('slides', 'Slides/Apresentação'), ('video', 'Vídeo'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='escola.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='escola.professor')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='escola.turma')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-data_upload'],
            },
        ),
    ]
