# Generated by Django 5.2.8 on 2025-12-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_horarioaula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioaula',
            options={'ordering': ['hora_inicio', 'dia_semana'], 'verbose_name': 'Horário de Aula', 'verbose_name_plural': 'Horários de Aula'},
        ),
    ]
