# Generated by Django 5.2.8 on 2025-12-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_sala_aviso_ativo_aviso_autor_aviso_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='escola.disciplina'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='escola.turma'),
        ),
    ]
