# Generated by Django 5.2.8 on 2025-12-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_justificativafalta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
