# Generated by Django 5.2.8 on 2025-12-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_alter_documento_options_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='professores_fotos/'),
        ),
    ]
